from django.conf import settings

from influxdb import InfluxDBClient

import logging

logger = logging.getLogger(__name__)

sp500 = {'A': 'Agilent Technologies Inc',
         'AAL': 'American Airlines Group',
         'AAP': 'Advance Auto Parts',
         'AAPL': 'Apple Inc.',
         'ABBV': 'AbbVie Inc.',
         'ABC': 'AmerisourceBergen Corp',
         'ABMD': 'ABIOMED Inc',
         'ABT': 'Abbott Laboratories',
         'ACN': 'Accenture plc',
         'ADBE': 'Adobe Systems Inc',
         'ADI': 'Analog Devices, Inc.',
         'ADM': 'Archer-Daniels-Midland Co',
         'ADP': 'Automatic Data Processing',
         'ADS': 'Alliance Data Systems',
         'ADSK': 'Autodesk Inc.',
         'AEE': 'Ameren Corp',
         'AEP': 'American Electric Power',
         'AES': 'AES Corp',
         'AET': 'Aetna Inc',
         'AFL': 'AFLAC Inc',
         'AGN': 'Allergan, Plc',
         'AIG': 'American International Group, Inc.',
         'AIV': 'Apartment Investment & Management (Aimco)',
         'AIZ': 'Assurant Inc.',
         'AJG': 'Arthur J. Gallagher & Co.',
         'AKAM': 'Akamai Technologies Inc',
         'ALB': 'Albemarle Corp',
         'ALGN': 'Align Technology',
         'ALK': 'Alaska Air Group Inc',
         'ALL': 'Allstate Corp',
         'ALLE': 'Allegion',
         'ALXN': 'Alexion Pharmaceuticals',
         'AMAT': 'Applied Materials Inc.',
         'AMD': 'Advanced Micro Devices Inc',
         'AME': 'AMETEK Inc.',
         'AMG': 'Affiliated Managers Group Inc',
         'AMGN': 'Amgen Inc.',
         'AMP': 'Ameriprise Financial',
         'AMT': 'American Tower Corp.',
         'AMZN': 'Amazon.com Inc.',
         'ANET': 'Arista Networks',
         'ANSS': 'ANSYS',
         'ANTM': 'Anthem Inc.',
         'AON': 'Aon plc',
         'AOS': 'A.O. Smith Corp',
         'APA': 'Apache Corporation',
         'APC': 'Anadarko Petroleum Corp',
         'APD': 'Air Products & Chemicals Inc',
         'APH': 'Amphenol Corp',
         'APTV': 'Aptiv Plc',
         'ARE': 'Alexandria Real Estate Equities Inc',
         'ARNC': 'Arconic Inc.',
         'ATVI': 'Activision Blizzard',
         'AVB': 'AvalonBay Communities, Inc.',
         'AVGO': 'Broadcom',
         'AVY': 'Avery Dennison Corp',
         'AWK': 'American Water Works Company Inc',
         'AXP': 'American Express Co',
         'AZO': 'AutoZone Inc',
         'BA': 'Boeing Company',
         'BAC': 'Bank of America Corp',
         'BAX': 'Baxter International Inc.',
         'BBT': 'BB&T Corporation',
         'BBY': 'Best Buy Co. Inc.',
         'BDX': 'Becton Dickinson',
         'BEN': 'Franklin Resources',
         'BF.B': 'Brown-Forman Corp.',
         'BHF': 'Brighthouse Financial Inc',
         'BHGE': 'Baker Hughes, a GE Company',
         'BIIB': 'Biogen Inc.',
         'BK': 'The Bank of New York Mellon Corp.',
         'BKNG': 'Booking Holdings Inc',
         'BLK': 'BlackRock',
         'BLL': 'Ball Corp',
         'BMY': 'Bristol-Myers Squibb',
         'BR': 'Broadridge Financial Solutions',
         'BRK.B': 'Berkshire Hathaway',
         'BSX': 'Boston Scientific',
         'BWA': 'BorgWarner',
         'BXP': 'Boston Properties',
         'C': 'Citigroup Inc.',
         'CA': 'CA, Inc.',
         'CAG': 'Conagra Brands',
         'CAH': 'Cardinal Health Inc.',
         'CAT': 'Caterpillar Inc.',
         'CB': 'Chubb Limited',
         'CBOE': 'Cboe Global Markets',
         'CBRE': 'CBRE Group',
         'CBS': 'CBS Corp.',
         'CCI': 'Crown Castle International Corp.',
         'CCL': 'Carnival Corp.',
         'CDNS': 'Cadence Design Systems',
         'CELG': 'Celgene Corp.',
         'CERN': 'Cerner',
         'CF': 'CF Industries Holdings Inc',
         'CFG': 'Citizens Financial Group',
         'CHD': 'Church & Dwight',
         'CHRW': 'C. H. Robinson Worldwide',
         'CHTR': 'Charter Communications',
         'CI': 'CIGNA Corp.',
         'CINF': 'Cincinnati Financial',
         'CL': 'Colgate-Palmolive',
         'CLX': 'The Clorox Company',
         'CMA': 'Comerica Inc.',
         'CMCSA': 'Comcast Corp.',
         'CME': 'CME Group Inc.',
         'CMG': 'Chipotle Mexican Grill',
         'CMI': 'Cummins Inc.',
         'CMS': 'CMS Energy',
         'CNC': 'Centene Corporation',
         'CNP': 'CenterPoint Energy',
         'COF': 'Capital One Financial',
         'COG': 'Cabot Oil & Gas',
         'COL': 'Rockwell Collins',
         'COO': 'The Cooper Companies',
         'COP': 'ConocoPhillips',
         'COST': 'Costco Wholesale Corp.',
         'COTY': 'Coty, Inc',
         'CPB': 'Campbell Soup',
         'CPRT': 'Copart Inc',
         'CRM': 'Salesforce.com',
         'CSCO': 'Cisco Systems',
         'CSX': 'CSX Corp.',
         'CTAS': 'Cintas Corporation',
         'CTL': 'CenturyLink Inc',
         'CTSH': 'Cognizant Technology Solutions',
         'CTXS': 'Citrix Systems',
         'CVS': 'CVS Health',
         'CVX': 'Chevron Corp.',
         'CXO': 'Concho Resources',
         'D': 'Dominion Energy',
         'DAL': 'Delta Air Lines Inc.',
         'DE': 'Deere & Co.',
         'DFS': 'Discover Financial Services',
         'DG': 'Dollar General',
         'DGX': 'Quest Diagnostics',
         'DHI': 'D. R. Horton',
         'DHR': 'Danaher Corp.',
         'DIS': 'The Walt Disney Company',
         'DISCA': 'Discovery Inc. Class A',
         'DISCK': 'Discovery Inc. Class C',
         'DISH': 'Dish Network',
         'DLR': 'Digital Realty Trust Inc',
         'DLTR': 'Dollar Tree',
         'DOV': 'Dover Corp.',
         'DRE': 'Duke Realty Corp',
         'DRI': 'Darden Restaurants',
         'DTE': 'DTE Energy Co.',
         'DUK': 'Duke Energy',
         'DVA': 'DaVita Inc.',
         'DVN': 'Devon Energy Corp.',
         'DWDP': 'DowDuPont',
         'DXC': 'DXC Technology',
         'EA': 'Electronic Arts',
         'EBAY': 'eBay Inc.',
         'ECL': 'Ecolab Inc.',
         'ED': 'Consolidated Edison',
         'EFX': 'Equifax Inc.',
         'EIX': "Edison Int'l",
         'EL': 'Estee Lauder Cos.',
         'EMN': 'Eastman Chemical',
         'EMR': 'Emerson Electric Company',
         'EOG': 'EOG Resources',
         'EQIX': 'Equinix',
         'EQR': 'Equity Residential',
         'EQT': 'EQT Corporation',
         'ES': 'Eversource Energy',
         'ESRX': 'Express Scripts',
         'ESS': 'Essex Property Trust, Inc.',
         'ETFC': 'E*Trade',
         'ETN': 'Eaton Corporation',
         'ETR': 'Entergy Corp.',
         'EVRG': 'Evergy',
         'EW': 'Edwards Lifesciences',
         'EXC': 'Exelon Corp.',
         'EXPD': 'Expeditors',
         'EXPE': 'Expedia Group',
         'EXR': 'Extra Space Storage',
         'F': 'Ford Motor',
         'FAST': 'Fastenal Co',
         'FB': 'Facebook, Inc.',
         'FBHS': 'Fortune Brands Home & Security',
         'FCX': 'Freeport-McMoRan Inc.',
         'FDX': 'FedEx Corporation',
         'FE': 'FirstEnergy Corp',
         'FFIV': 'F5 Networks',
         'FIS': 'Fidelity National Information Services',
         'FISV': 'Fiserv Inc',
         'FITB': 'Fifth Third Bancorp',
         'FL': 'Foot Locker Inc',
         'FLIR': 'FLIR Systems',
         'FLR': 'Fluor Corp.',
         'FLS': 'Flowserve Corporation',
         'FLT': 'FleetCor Technologies Inc',
         'FMC': 'FMC Corporation',
         'FOX': 'Twenty-First Century Fox Class B',
         'FOXA': 'Twenty-First Century Fox Class A',
         'FRT': 'Federal Realty Investment Trust',
         'FTI': 'TechnipFMC',
         'FTNT': 'Fortinet',
         'FTV': 'Fortive Corp',
         'GD': 'General Dynamics',
         'GE': 'General Electric',
         'GILD': 'Gilead Sciences',
         'GIS': 'General Mills',
         'GLW': 'Corning Inc.',
         'GM': 'General Motors',
         'GOOG': 'Alphabet Inc Class C',
         'GOOGL': 'Alphabet Inc Class A',
         'GPC': 'Genuine Parts',
         'GPN': 'Global Payments Inc.',
         'GPS': 'Gap Inc.',
         'GRMN': 'Garmin Ltd.',
         'GS': 'Goldman Sachs Group',
         'GT': 'Goodyear Tire & Rubber',
         'GWW': 'Grainger (W.W.) Inc.',
         'HAL': 'Halliburton Co.',
         'HAS': 'Hasbro Inc.',
         'HBAN': 'Huntington Bancshares',
         'HBI': 'Hanesbrands Inc',
         'HCA': 'HCA Holdings',
         'HCP': 'HCP Inc.',
         'HD': 'Home Depot',
         'HES': 'Hess Corporation',
         'HFC': 'HollyFrontier Corp',
         'HIG': 'Hartford Financial Svc.Gp.',
         'HII': 'Huntington Ingalls Industries',
         'HLT': 'Hilton Worldwide Holdings Inc',
         'HOG': 'Harley-Davidson',
         'HOLX': 'Hologic',
         'HON': "Honeywell Int'l Inc.",
         'HP': 'Helmerich & Payne',
         'HPE': 'Hewlett Packard Enterprise',
         'HPQ': 'HP Inc.',
         'HRB': 'Block H&R',
         'HRL': 'Hormel Foods Corp.',
         'HRS': 'Harris Corporation',
         'HSIC': 'Henry Schein',
         'HST': 'Host Hotels & Resorts',
         'HSY': 'The Hershey Company',
         'HUM': 'Humana Inc.',
         'IBM': 'International Business Machines',
         'ICE': 'Intercontinental Exchange',
         'IDXX': 'IDEXX Laboratories',
         'IFF': 'Intl Flavors & Fragrances',
         'ILMN': 'Illumina Inc',
         'INCY': 'Incyte',
         'INFO': 'IHS Markit Ltd.',
         'INTC': 'Intel Corp.',
         'INTU': 'Intuit Inc.',
         'IP': 'International Paper',
         'IPG': 'Interpublic Group',
         'IPGP': 'IPG Photonics Corp.',
         'IQV': 'IQVIA Holdings Inc.',
         'IR': 'Ingersoll-Rand PLC',
         'IRM': 'Iron Mountain Incorporated',
         'ISRG': 'Intuitive Surgical Inc.',
         'IT': 'Gartner Inc',
         'ITW': 'Illinois Tool Works',
         'IVZ': 'Invesco Ltd.',
         'JBHT': 'J. B. Hunt Transport Services',
         'JCI': 'Johnson Controls International',
         'JEC': 'Jacobs Engineering Group',
         'JEF': 'Jefferies Financial Group',
         'JNJ': 'Johnson & Johnson',
         'JNPR': 'Juniper Networks',
         'JPM': 'JPMorgan Chase & Co.',
         'JWN': 'Nordstrom',
         'K': 'Kellogg Co.',
         'KEY': 'KeyCorp',
         'KHC': 'Kraft Heinz Co',
         'KIM': 'Kimco Realty',
         'KLAC': 'KLA-Tencor Corp.',
         'KMB': 'Kimberly-Clark',
         'KMI': 'Kinder Morgan',
         'KMX': 'Carmax Inc',
         'KO': 'Coca-Cola Company (The)',
         'KORS': 'Michael Kors Holdings',
         'KR': 'Kroger Co.',
         'KSS': "Kohl's Corp.",
         'KSU': 'Kansas City Southern',
         'L': 'Loews Corp.',
         'LB': 'L Brands Inc.',
         'LEG': 'Leggett & Platt',
         'LEN': 'Lennar Corp.',
         'LH': 'Laboratory Corp. of America Holding',
         'LKQ': 'LKQ Corporation',
         'LLL': 'L-3 Communications Holdings',
         'LLY': 'Lilly (Eli) & Co.',
         'LMT': 'Lockheed Martin Corp.',
         'LNC': 'Lincoln National',
         'LNT': 'Alliant Energy Corp',
         'LOW': "Lowe's Cos.",
         'LRCX': 'Lam Research',
         'LUV': 'Southwest Airlines',
         'LYB': 'LyondellBasell',
         'M': "Macy's Inc.",
         'MA': 'Mastercard Inc.',
         'MAA': 'Mid-America Apartments',
         'MAC': 'Macerich',
         'MAR': "Marriott Int'l.",
         'MAS': 'Masco Corp.',
         'MAT': 'Mattel Inc.',
         'MCD': "McDonald's Corp.",
         'MCHP': 'Microchip Technology',
         'MCK': 'McKesson Corp.',
         'MCO': "Moody's Corp",
         'MDLZ': 'Mondelez International',
         'MDT': 'Medtronic plc',
         'MET': 'MetLife Inc.',
         'MGM': 'MGM Resorts International',
         'MHK': 'Mohawk Industries',
         'MKC': 'McCormick & Co.',
         'MLM': 'Martin Marietta Materials',
         'MMC': 'Marsh & McLennan',
         'MMM': '3M Company',
         'MNST': 'Monster Beverage',
         'MO': 'Altria Group Inc',
         'MOS': 'The Mosaic Company',
         'MPC': 'Marathon Petroleum',
         'MRK': 'Merck & Co.',
         'MRO': 'Marathon Oil Corp.',
         'MS': 'Morgan Stanley',
         'MSCI': 'MSCI Inc',
         'MSFT': 'Microsoft Corp.',
         'MSI': 'Motorola Solutions Inc.',
         'MTB': 'M&T Bank Corp.',
         'MTD': 'Mettler Toledo',
         'MU': 'Micron Technology',
         'MYL': 'Mylan N.V.',
         'NBL': 'Noble Energy Inc',
         'NCLH': 'Norwegian Cruise Line',
         'NDAQ': 'Nasdaq, Inc.',
         'NEE': 'NextEra Energy',
         'NEM': 'Newmont Mining Corporation',
         'NFLX': 'Netflix Inc.',
         'NFX': 'Newfield Exploration Co',
         'NI': 'NiSource Inc.',
         'NKE': 'Nike',
         'NKTR': 'Nektar Therapeutics',
         'NLSN': 'Nielsen Holdings',
         'NOC': 'Northrop Grumman Corp.',
         'NOV': 'National Oilwell Varco Inc.',
         'NRG': 'NRG Energy',
         'NSC': 'Norfolk Southern Corp.',
         'NTAP': 'NetApp',
         'NTRS': 'Northern Trust Corp.',
         'NUE': 'Nucor Corp.',
         'NVDA': 'Nvidia Corporation',
         'NWL': 'Newell Brands',
         'NWS': 'News Corp. Class B',
         'NWSA': 'News Corp. Class A',
         'O': 'Realty Income Corporation',
         'OKE': 'ONEOK',
         'OMC': 'Omnicom Group',
         'ORCL': 'Oracle Corp.',
         'ORLY': "O'Reilly Automotive",
         'OXY': 'Occidental Petroleum',
         'PAYX': 'Paychex Inc.',
         'PBCT': "People's United Financial",
         'PCAR': 'PACCAR Inc.',
         'PCG': 'PG&E Corp.',
         'PEG': 'Public Serv. Enterprise Inc.',
         'PEP': 'PepsiCo Inc.',
         'PFE': 'Pfizer Inc.',
         'PFG': 'Principal Financial Group',
         'PG': 'Procter & Gamble',
         'PGR': 'Progressive Corp.',
         'PH': 'Parker-Hannifin',
         'PHM': 'Pulte Homes Inc.',
         'PKG': 'Packaging Corporation of America',
         'PKI': 'PerkinElmer',
         'PLD': 'Prologis',
         'PM': 'Philip Morris International',
         'PNC': 'PNC Financial Services',
         'PNR': 'Pentair plc',
         'PNW': 'Pinnacle West Capital',
         'PPG': 'PPG Industries',
         'PPL': 'PPL Corp.',
         'PRGO': 'Perrigo',
         'PRU': 'Prudential Financial',
         'PSA': 'Public Storage',
         'PSX': 'Phillips 66',
         'PVH': 'PVH Corp.',
         'PWR': 'Quanta Services Inc.',
         'PX': 'Praxair Inc.',
         'PXD': 'Pioneer Natural Resources',
         'PYPL': 'PayPal',
         'QCOM': 'QUALCOMM Inc.',
         'QRVO': 'Qorvo',
         'RCL': 'Royal Caribbean Cruises Ltd',
         'RE': 'Everest Re Group Ltd.',
         'REG': 'Regency Centers Corporation',
         'REGN': 'Regeneron',
         'RF': 'Regions Financial Corp.',
         'RHI': 'Robert Half International',
         'RHT': 'Red Hat Inc.',
         'RJF': 'Raymond James Financial Inc.',
         'RL': 'Polo Ralph Lauren Corp.',
         'RMD': 'ResMed',
         'ROK': 'Rockwell Automation Inc.',
         'ROL': 'Rollins Inc.',
         'ROP': 'Roper Technologies',
         'ROST': 'Ross Stores',
         'RSG': 'Republic Services Inc',
         'RTN': 'Raytheon Co.',
         'SBAC': 'SBA Communications',
         'SBUX': 'Starbucks Corp.',
         'SCG': 'SCANA Corp',
         'SCHW': 'Charles Schwab Corporation',
         'SEE': 'Sealed Air',
         'SHW': 'Sherwin-Williams',
         'SIVB': 'SVB Financial',
         'SJM': 'JM Smucker',
         'SLB': 'Schlumberger Ltd.',
         'SLG': 'SL Green Realty',
         'SNA': 'Snap-on',
         'SNPS': 'Synopsys Inc.',
         'SO': 'Southern Co.',
         'SPG': 'Simon Property Group Inc',
         'SPGI': 'S&P Global, Inc.',
         'SRCL': 'Stericycle Inc',
         'SRE': 'Sempra Energy',
         'STI': 'SunTrust Banks',
         'STT': 'State Street Corp.',
         'STX': 'Seagate Technology',
         'STZ': 'Constellation Brands',
         'SWK': 'Stanley Black & Decker',
         'SWKS': 'Skyworks Solutions',
         'SYF': 'Synchrony Financial',
         'SYK': 'Stryker Corp.',
         'SYMC': 'Symantec Corp.',
         'SYY': 'Sysco Corp.',
         'T': 'AT&T Inc.',
         'TAP': 'Molson Coors Brewing Company',
         'TDG': 'TransDigm Group',
         'TEL': 'TE Connectivity Ltd.',
         'TGT': 'Target Corp.',
         'TIF': 'Tiffany & Co.',
         'TJX': 'TJX Companies Inc.',
         'TMK': 'Torchmark Corp.',
         'TMO': 'Thermo Fisher Scientific',
         'TPR': 'Tapestry, Inc.',
         'TRIP': 'TripAdvisor',
         'TROW': 'T. Rowe Price Group',
         'TRV': 'The Travelers Companies Inc.',
         'TSCO': 'Tractor Supply Company',
         'TSN': 'Tyson Foods',
         'TSS': 'Total System Services',
         'TTWO': 'Take-Two Interactive',
         'TWTR': 'Twitter, Inc.',
         'TXN': 'Texas Instruments',
         'TXT': 'Textron Inc.',
         'UA': 'Under Armour Class C',
         'UAA': 'Under Armour Class A',
         'UAL': 'United Continental Holdings',
         'UDR': 'UDR Inc',
         'UHS': 'Universal Health Services, Inc.',
         'ULTA': 'Ulta Beauty',
         'UNH': 'United Health Group Inc.',
         'UNM': 'Unum Group',
         'UNP': 'Union Pacific',
         'UPS': 'United Parcel Service',
         'URI': 'United Rentals, Inc.',
         'USB': 'U.S. Bancorp',
         'UTX': 'United Technologies',
         'V': 'Visa Inc.',
         'VAR': 'Varian Medical Systems',
         'VFC': 'V.F. Corp.',
         'VIAB': 'Viacom Inc.',
         'VLO': 'Valero Energy',
         'VMC': 'Vulcan Materials',
         'VNO': 'Vornado Realty Trust',
         'VRSK': 'Verisk Analytics',
         'VRSN': 'Verisign Inc.',
         'VRTX': 'Vertex Pharmaceuticals Inc',
         'VTR': 'Ventas Inc',
         'VZ': 'Verizon Communications',
         'WAT': 'Waters Corporation',
         'WBA': 'Walgreens Boots Alliance',
         'WCG': 'WellCare',
         'WDC': 'Western Digital',
         'WEC': 'Wec Energy Group Inc',
         'WELL': 'Welltower Inc.',
         'WFC': 'Wells Fargo',
         'WHR': 'Whirlpool Corp.',
         'WLTW': 'Willis Towers Watson',
         'WM': 'Waste Management Inc.',
         'WMB': 'Williams Cos.',
         'WMT': 'Walmart',
         'WRK': 'WestRock',
         'WU': 'Western Union Co',
         'WY': 'Weyerhaeuser',
         'WYNN': 'Wynn Resorts Ltd',
         'XEC': 'Cimarex Energy',
         'XEL': 'Xcel Energy Inc',
         'XLNX': 'Xilinx',
         'XOM': 'Exxon Mobil Corp.',
         'XRAY': 'Dentsply Sirona',
         'XRX': 'Xerox',
         'XYL': 'Xylem Inc.',
         'YUM': 'Yum! Brands Inc',
         'ZBH': 'Zimmer Biomet Holdings',
         'ZION': 'Zions Bancorp',
         'ZTS': 'Zoetis'}


def get_influxdb_client():
    """Returns an ``InfluxDBClient`` instance."""
    client = InfluxDBClient(
        settings.INFLUXDB_HOST,
        settings.INFLUXDB_PORT,
        settings.INFLUXDB_USERNAME,
        settings.INFLUXDB_PASSWORD,
        settings.INFLUXDB_DATABASE,
        timeout=getattr(settings, 'INFLUXDB_TIMEOUT', 10),
        ssl=getattr(settings, 'INFLUXDB_SSL', False),
        verify_ssl=getattr(settings, 'INFLUXDB_VERIFY_SSL', False),
    )
    return client


def query(client, stock_symbol):
    query = 'select "' + stock_symbol + '" from price;'
    print("Querying data: " + query)
    result = client.query(query, epoch='ms')
    print("Result: {0}".format(result))
    return result
